[auth.external.google]
enabled = true
client_id = "IDs176863184639-720tbn3vuuhkf1sjv8uoo5l9t1fajmfq.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false
