services:
  frontend:
    build:
      context: .
    ports:
      - "5173:80"
    networks:
      - family-backend
    restart: unless-stopped

networks:
  family-backend:
    external: true
    name: family-app-go_default
